baseurl: /
repository: phpearth/php-lands
title: The PHP Lands
description: Explore the PHP language and ecosystem in a fun and interactive way using a pirate map.
exclude:
  - bin
  - node_modules
  - src
  - .editorconfig
  - CNAME
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Makefile
  - map.jpg
  - package.json
  - package-lock.json
  - README.md
  - webpack.config.js
  - yarn.lock
  - yarn-error.log
app:
  map_url: https://raw.githubusercontent.com/phpearth/assets/master/php-lands/2022/v1.2
  asset_version: v8
